### PR TITLE
Move fixtures to conftest.py

### PR DESCRIPTION
**Pull request by athos-ribeiro**
To avoid PyFlakes F811 warnings regarding redefinition of unused names
when importing and using fixtures, we move our fixtures module to
conftest.py. See
https://docs.pytest.org/en/latest/fixture.html#conftest-py and the
discussion in #1093 for reference.

Signed-off-by: Athos Ribeiro <athos@redhat.com>

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Builds fail due to issue pointed in #1096. Will rebase after it is merged.

File: tests/test_cli.py [hunk 1]
```diff
@@ -44,6 +44,11 @@
     ('path', DOCKERFILE_OK_PATH),
 ])
 
+
+def get_uuid():
```
Comment (lcarva) [inline tests/test_cli.py]: Can we turn this into a proper fixture in conftest.py?
```python
@pytest.fixture()      
def uuid_value():                                                    
    return uuid.uuid4().hex                                        
                                                                   
                                                                   
@pytest.fixture()                                                  
def temp_image_name(uuid_value):                                             
    return ImageName(repo=("atomic-reactor-tests-%s" % uuid_value))
```

That way we don't need to redefine it here.

**Comment by lcarva** [comment]
@athos-ribeiro, there are quite a few `# noqa` comments left. Can those be removed?
```
🐚 git grep -w noqa tests | wc -l
213
```
Some of it are unrelated to fixture redefinition though.

**Comment by lcarva** [comment]
I think the coverage drop is because for some reason coveralls didn't pick up the python 3 test results.

**Comment by mlangsdorf** [comment]
I am completely in favor of never having to write   # noqa:F811 again and needing to guess which decorator line that stickler-ci think needs it.

File: tests/test_cli.py (hunk 1 above)
Comment (athos-ribeiro) [reply tests/test_cli.py]: Since we are only using it in the other fixture and in a setup_method, maybe we should either move it to `tests/util.py` or just go ahead and make the calls to uuid directly instead of having a function?

**Comment by athos-ribeiro** [comment]
@lcarva, the other `# noqa` comments are not related to this issue. There are a few `# noqa: F811` left, but then I realized that the space after the colon makes it ignore everything, not only F811 warnings.

File: tests/test_cli.py (hunk 1 above)
Comment (lcarva) [reply tests/test_cli.py]: WFM

Comment (athos-ribeiro) [reply tests/test_cli.py]: Done

**Comment by MartinBasti** [comment]
Tests only, update of release notes is not needed
